// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bezyzzdpqhomvmmhemsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlenl6emRwcWhvbXZtbWhlbXN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDcwNDQsImV4cCI6MjA3NDIyMzA0NH0.-W3czHc7uShVqb_gpSk53lSfGJVJ5oA-VY1an5Bd2BQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});